require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/categories", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Category. As you add validations to Category, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      name: "Terror",
      description: "Descripción de terror"
    }
  end 

  let(:invalid_attributes)do
    {
      name: nil,
      description: "Descripción de terror"
    }
  
  end 

    describe "GET /api/categories" do
      it "debe mostrar listado de categorias" do
        get categories_path
        expect(response).to have_http_status(200)
      end
    end
  
    describe "GET /api/categories" do
      let(:category) { create :category } 
      it "debe mostrar una categoria" do
        get category_path category.id
        expect(response).to have_http_status(200)
      end
    end

end